import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {mathAction,renderMath} from '../dist/math.js';
const data=JSON.parse(fs.readFileSync('dist/data/math.json'));
function context(a){return {math:data,state:{pending:{id:a.id,kind:a.kind||'counting',touched:[],answer:'',errors:0,help:false},settings:{}},save(){},render(){},attempt(){},speak(){},toast(){}};}
test('respuesta directa sincroniza todos los objetos con el resultado',()=>{for(const a of data.arithmetic){const c=context(a);mathAction(c,'number-answer',{dataset:{value:String(a.answer)}});assert.equal(c.state.pending.touched.length,a.b,a.id);const html=renderMath(c);if(a.mode==='objects')assert.ok(html.includes(`<strong>${a.answer}</strong>`),a.id);}});
test('un objeto contado dos veces se desmarca sin contar dos veces',()=>{const a=data.counting.find(a=>a.type==='objects'),c=context(a);mathAction(c,'count-object',{dataset:{value:'0'}});assert.equal(c.state.pending.touched.length,1);mathAction(c,'count-object',{dataset:{value:'0'}});assert.equal(c.state.pending.touched.length,0);});
test('error no se registra como acierto y ofrece ayuda concreta',()=>{const a=data.arithmetic[0],c=context(a);let records=0;c.attempt=()=>records++;mathAction(c,'number-answer',{dataset:{value:'99'}});assert.equal(records,0);assert.equal(c.state.pending.errors,1);assert.equal(c.state.pending.feedback,a.hint);});
test('respuesta de teclado no convierte vacío en cero',()=>{const a=data.arithmetic.find(a=>a.answer===0),c=context(a);let records=0;c.attempt=()=>records++;mathAction(c,'key',{dataset:{value:'✓'}});assert.equal(records,0);mathAction(c,'key',{dataset:{value:'0'}});mathAction(c,'key',{dataset:{value:'✓'}});assert.equal(records,1);});
test('agrupar es manipulación normal, sin registrar que se pidió una pista',()=>{const a=data.counting.find(a=>a.type==='tens'),c=context(a);mathAction(c,'group-ten',{dataset:{}});assert.equal(c.state.pending.help,false);});
test('las decenas dadas por el enunciado de unidades ya están agrupadas',()=>{for(const a of data.counting.filter(a=>a.type==='tens'&&a.ask==='units')){const c=context(a);assert.ok(renderMath(c).includes(`aria-label="${Math.floor(a.number/10)} decenas y ${a.number%10} unidades sueltas"`),a.id);}});
